import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SideBar from "./components/common/Sidebar/sidebar"



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Management',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <SideBar />
        <main style={{ marginLeft: "120px" }}>
          {children}
        </main>
        
      </body>
    </html>

  )
}
